### PR TITLE
Fix bottom white space

### PR DESCRIPTION
**Pull request by Axrorxoja**

### CODE REVIEW

**Comment by Axrorxoja** [comment]
@googlebot I signed it!

**Comment by thatfiredev** [comment]
@Axrorxoja That commit has been signed with the username Akhrorkhoja. Be sure to use that username when signing the CLA

**Comment by Axrorxoja** [comment]
@googlebot I signed it!

**Comment by Axrorxoja** [comment]
@rosariopfernandes I changed CLA username 
what I need after that ?

**Comment by thatfiredev** [comment]
@Axrorxoja uh, I'm not sure. Better wait for a Googler to verify it

**Comment by Axrorxoja** [comment]
@googlebot I signed it!

**Comment by Axrorxoja** [comment]
@rosariopfernandes how can fix it, please help :)

**Comment by thatfiredev** [comment]
@Axrorxoja as I said, a Googler can verify that you signed the CLA.

An alternative would be to close this PR and open a new one, but make sure that this time you sign the commit with the username "Axrorxoja".

**Review by lucazin — APPROVED** [review]

**Pull request closed without merging**
