### PR TITLE
Use string templates

### PR DESCRIPTION
**Pull request by thatfiredev**
This PR should:
- [x] ~Replace findViewById() with synthetic binding~
- [x] Replace string concatenation with string templates
- [x] Update gradle tools version

### CODE REVIEW

**Review by zhouyiself — COMMENTED** [review]
Hmm, kotlinx synthetic seems no longer a recommendation.
https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended/efdvpkg/?utm_source=share&utm_medium=web2x

**Comment by thatfiredev** [comment]
@zhouyiself I wasn't aware of it, thanks for pointing me to that thread. 

I've updated my PR to keep findViewById and use string templates.

**Comment by thatfiredev** [comment]
Thanks @zhouyiself 

On a side note: maybe use "Squash and merge" next time? Just to keep the commit history clean.

**Comment by zhouyiself** [comment]
Right, clicked too fast...

**Pull request merged**
